[project]
name = "mlwpython"
version = "0.1.0"
description = "ML with python"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "ipykernel>=7.1.0",
    "matplotlib>=3.10.8",
    "pandas>=3.0.0",
    "scikit-learn>=1.8.0",
    "torch>=2.10.0"
]